PENDING = "PENDING"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
ARCHIVED = "ARCHIVED"
STATUS_CHOICES = (
    (PENDING, PENDING),
    (APPROVED, APPROVED),
    (REJECTED, REJECTED),
    (ARCHIVED, ARCHIVED),
)
